=== loicoudot/java4cpp-core/mappings.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" version="1.0" targetNamespace="http://java4cpp.loicoudot.github.com" xmlns:tns="http://java4cpp.loicoudot.github.com" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="mappings" type="tns:mappings"/>

  <xs:complexType name="mappings" final="extension restriction">
    <xs:sequence>
      <xs:element name="namespaces" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="namespace" type="tns:namespace" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="classes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="class" type="tns:classMapping" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="keywords" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="keyword" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="namespace" final="extension restriction">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="package" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="classMapping" final="extension restriction">
    <xs:sequence>
      <xs:element name="cppName" type="xs:string" minOccurs="0"/>
      <xs:element name="interfaces" type="tns:wrappes" minOccurs="0"/>
      <xs:element name="innerClasses" type="tns:wrappes" minOccurs="0"/>
      <xs:element name="staticFields" type="tns:wrappes" minOccurs="0"/>
      <xs:element name="constructors" type="tns:wrappes" minOccurs="0"/>
      <xs:element name="methods" type="tns:wrappes" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="class" type="xs:string"/>
    <xs:attribute name="exportAll" type="xs:boolean"/>
    <xs:attribute name="exportFields" type="xs:boolean"/>
    <xs:attribute name="interfaceAll" type="xs:boolean"/>
    <xs:attribute name="superclass" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="wrappes" final="extension restriction">
    <xs:sequence>
      <xs:element name="noWrappes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="noWrappe" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="wrappes" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="wrappe" type="tns:wrappe" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="wrappe" final="extension restriction">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="cppName" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== loicoudot/java4cpp-core/src/test/resources/mappings.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mappings xmlns="http://java4cpp.loicoudot.github.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java4cpp.loicoudot.github.com http://raw.github.com/loicoudot/java4cpp-core/master/mappings.xsd">
	<namespaces>
		<namespace package="com.github.loicoudot">java4cpp</namespace>
		<namespace package="java.utils.*">utils</namespace>
	</namespaces>
	<classes>
		<class superclass="true" interfaceAll="true" exportFields="true"
			exportAll="false" class="java.lang.Float">
			<cppName>cppName</cppName>
			<interfaces>
				<noWrappes>
					<noWrappe>Interface1</noWrappe>
					<noWrappe>Interface2</noWrappe>
				</noWrappes>
				<wrappes>
					<wrappe>com.github.loicoudot.java4cpp.Empty1</wrappe>
					<wrappe cppName="cppInterface">Interface2</wrappe>
				</wrappes>
			</interfaces>
			<innerClasses>
				<noWrappes>
					<noWrappe>noWrappe1</noWrappe>
				</noWrappes>
				<wrappes>
					<wrappe cppName="cppInner">Inner1</wrappe>
				</wrappes>
			</innerClasses>
			<staticFields>
				<noWrappes>
					<noWrappe>field1</noWrappe>
				</noWrappes>
				<wrappes>
					<wrappe cppName="fieldCpp">staticField1</wrappe>
				</wrappes>
			</staticFields>
			<constructors>
				<noWrappes>
					<noWrappe>noWrappe1</noWrappe>
					<noWrappe>noWrappe2</noWrappe>
				</noWrappes>
				<wrappes>
					<wrappe cppName="cppName"></wrappe>
					<wrappe>wrappe2</wrappe>
				</wrappes>
			</constructors>
			<methods>
				<noWrappes>
					<noWrappe>method2()</noWrappe>
				</noWrappes>
				<wrappes>
					<wrappe>method1()</wrappe>
				</wrappes>
			</methods>
		</class>
	</classes>
	<keywords>
		<keyword>true</keyword>
		<keyword>delete</keyword>
	</keywords>
</mappings>
